# Generated by Django 4.1.3 on 2023-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(default='Тут пока ничего нету', verbose_name='Про себя(не обязательно)'),
        ),
    ]
