# Generated by Django 4.1.3 on 2022-12-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_blogcategory_image_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='image',
        ),
    ]
