# Generated by Django 4.1.3 on 2022-12-26 16:36

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/article/', verbose_name='Аватарка автора'),
        ),
    ]
