# Generated by Django 4.1.3 on 2023-02-28 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comments_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
    ]
