# Generated by Django 4.1.3 on 2023-02-28 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comments_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
    ]
