# Generated by Django 4.1.3 on 2023-02-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
