# Generated by Django 4.1.3 on 2023-02-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_comments_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
