# Generated by Django 4.1.3 on 2023-02-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_category_meta_description_category_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='проверен'),
        ),
    ]
