# Generated by Django 4.1.3 on 2023-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверен'),
        ),
    ]
