# Generated by Django 4.1.3 on 2023-02-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_user'),
        ('main', '0002_alter_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Акьивировано')),
                ('product', models.ManyToManyField(to='catalog.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Карусель товаров',
                'verbose_name_plural': 'Карусель товаров',
                'ordering': ['sort'],
            },
        ),
    ]
