# Generated by Django 4.1.3 on 2023-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активировано'),
        ),
    ]
